Repository SeamusX7/ClubHub, pull requests merged in 2020-11, with the labels that each got.

#12 This is a test commit #6
  App.js
Labels: enhancement, front-end, navigation

#13 This is a test commit #4
  App.js
Labels: enhancement, front-end, navigation

#18 Created teams tab stack naivgation #4
  src/routes/TeamStack.js
  src/screens/team/Player.js
  src/screens/team/Team.js
Labels: front-end, navigation

#20 Fixed registration bug #19
  src/screens/RegistrationScreen/RegistrationScreen.js
Labels: bug

#21 Initial Home Stack Navigation #6
  src/routes/HomeStack.js
  src/screens/home/Home.js
Labels: front-end, navigation

#27 Updated home screen buttons to go to respective tab instead of adding…
  src/routes/HomeStack.js
  src/screens/home/Home.js
Labels: navigation

#28 Splash Screen and Icon addition #23
  src/assets/icon.png
  src/assets/splash.png
Labels: enhancement, front-end

#30 Created messages stack navigation #5
  src/routes/SessionStack.js
  src/routes/TeamStack.js
  src/screens/session/Message.js
  src/screens/session/Session.js
  src/screens/session/ViewMessage.js
  src/screens/team/Message.js
  src/screens/team/Team.js
  src/screens/team/ViewMessage.js
Labels: front-end, navigation

#31 Create Settings Stack Navigation #7
  src/routes/SettingsStack.js
  src/screens/settings/ClubHubPlus.js
  src/screens/settings/Customisation.js
  src/screens/settings/Language.js
  src/screens/settings/PrivacyPolicy.js
  src/screens/settings/Settings.js
  src/screens/settings/TermsOfService.js
  src/screens/settings/ViewProfile.js
Labels: front-end, navigation
