Repository SeamusX7/ClubHub, pull requests merged in 2021-03, with the labels that each got.

#221 Initial sessions redesign #213
  src/assets/styles/GlobalStyle.js
  src/assets/styles/MediumCardStyle.js
  src/assets/styles/SquareCardStyle.js
  src/components/OverflowMenuButton.js
  src/components/cards/MediumCard.js
  src/components/cards/SquareCard.js
  src/routes/SessionStack.js
  src/screens/session/Session.js
Labels: enhancement, front-end

#223 Continued sessions redesign #213
  src/assets/styles/GlobalStyle.js
  src/components/Search.js
  src/components/SearchButton.js
  src/components/buttons/FloatingModalButton.js
  src/screens/message/Message.js
  src/screens/session/PreviousGymSessions.js
  src/screens/session/PreviousMatchSessions.js
  src/screens/session/PreviousTrainingSessions.js
  src/screens/session/Session.js
Labels: enhancement, front-end

#224 #210 Initial Settings Re-Design
  src/components/SettingsButton.js
  src/screens/settings/Language.js
  src/screens/settings/PrivacyPolicy.js
  src/screens/settings/Settings.js
  src/screens/settings/TermsOfService.js
Labels: enhancement, front-end

#225 Initial team redesign #219
  src/assets/images/player-1.png
  src/assets/images/player-2.png
  src/assets/images/player-3.png
  src/assets/images/player-4.png
  src/assets/images/player-5.png
  src/assets/styles/LargeCardStyle.js
  src/assets/styles/MediumCardStyle.js
  src/assets/styles/ProfileStyle.js
  src/assets/styles/SquareCardStyle.js
  src/components/cards/LargeCard.js
  src/screens/team/Player.js
  src/screens/team/Team.js
Labels: enhancement, front-end

#226 Designed profile page #210
  src/screens/settings/Profile.js
Labels: enhancement, front-end

#227 214 notifications tab redesign
  App.js
  src/assets/styles/MediumCardStyle.js
  src/assets/styles/NotificationCardStyle.js
  src/components/buttons/AcceptInvitationButton.js
  src/components/buttons/DeclineInvitationButton.js
  src/components/buttons/ExpiredInvitationButton.js
  src/components/cards/NotificationCard.js
  src/routes/HomeStack.js
  src/routes/NotificationStack.js
  src/routes/SettingsStack.js
  src/routes/TabNavigator.js
  src/routes/TeamStack.js
  src/screens/home/Home.js
  src/screens/notification/Notification.js
  src/screens/team/Team.js
Labels: enhancement, front-end

#228 Continued changes to Settings Page #210
  src/assets/images/english.png
  src/assets/styles/SettingsCardDesign.js
  src/components/TopButton.js
  src/screens/settings/Language.js
  src/screens/settings/PrivacyPolicy.js
  src/screens/settings/Settings.js
  src/screens/settings/TermsOfService.js
Labels: enhancement, front-end

#231 Created duplicate medium card for player accessibility #230
  src/components/cards/MediumPlayerCard.js
  src/screens/team/Team.js
Labels: bug

#234 Updated choose team page to new design #229
  src/assets/styles/ModalStyle.js
  src/screens/RegistrationScreen/RegistrationScreen.js
  src/screens/launchpad/ChooseTeam.js
  src/screens/launchpad/DisplayTeams.js
Labels: enhancement, front-end

#239 Further development of sessions tab redesign #213
  src/assets/styles/GlobalStyle.js
  src/screens/session/Session.js
  src/screens/session/TabViewAttendance.js
  src/screens/session/TabViewInvitations.js
  src/screens/session/TabViewOverview.js
  src/screens/session/ViewUpcomingMatchSession.js
Labels: enhancement, front-end

#254 Fixed square card spacing issue on various screen sizes #247
  src/assets/styles/SquareCardStyle.js
  src/components/cards/SquareCardLeft.js
  src/components/cards/SquareCardRight.js
  src/screens/session/Session.js
  src/screens/settings/Profile.js
  src/screens/team/Player.js
  src/screens/team/Team.js
Labels: bug, front-end

#255 Redesigned news feed based on existing style #249
  .expo-shared/README.md
  app.json
  src/assets/images/kickout.jpg
  src/assets/styles/CardStyle.js
  src/assets/styles/NewsFeedStyle.js
  src/components/NewsFeedPost.js
  src/screens/home/Home.js
  src/screens/home/SpecificNewsFeedPost.js
Labels: front-end

#259 Styled chevron icon in stack navigation & made minor design changes #253
  src/components/buttons/CustomButton.js
  src/components/buttons/ModalSecondaryButton.js
  src/screens/home/SpecificNewsFeedPost.js
  src/screens/home/SpecificNewsFeedPostTemp1.js
  src/screens/home/SpecificNewsFeedPostTemp2.js
  src/screens/session/Attendance.js
  src/screens/session/Formation.js
  src/screens/session/Invitations.js
  src/screens/session/InvitePlayerModal.js
  src/screens/session/PreviousGymSessions.js
  src/screens/session/PreviousMatchSessions.js
  src/screens/session/PreviousTrainingSessions.js
  src/screens/session/ViewPreviousMatchSession.js
  src/screens/session/ViewUpcomingMatchSession.js
  src/screens/session/ViewUpcomingTrainingSession.js
  src/screens/settings/ClubHubPlus.js
  src/screens/settings/Language.js
  src/screens/settings/PrivacyPolicy.js
  src/screens/settings/Profile.js
  src/screens/settings/TermsOfService.js
  src/screens/settings/ViewProfile.js
  src/screens/team/Player.js
Labels: enhancement, front-end, navigation

#261 Designed half modals for overflow card menu #252
  src/assets/styles/HalfModalStyle.js
  src/components/buttons/HalfModalButton.js
  src/screens/launchpad/DisplayTeams.js
  src/screens/message/Message.js
  src/screens/session/PreviousGymSessions.js
  src/screens/session/PreviousMatchSessions.js
  src/screens/session/PreviousTrainingSessions.js
  src/screens/session/Session.js
  src/screens/team/Team.js
Labels: enhancement, front-end

#262 Initial Settings Page Icon Design #242
  src/components/SettingsButton.js
  src/components/TopButton.js
  src/screens/settings/Settings.js
Labels: enhancement, front-end

#263 Final Settings Button Design #242
  src/components/SettingsButton.js
  src/components/TopButton.js
Labels: enhancement, front-end

#264 Implementation for invitation status dropdowns minus chevrons #250
  package-lock.json
  package.json
  src/assets/styles/SmallCardStyle.js
  src/components/cards/SmallCard.js
  src/screens/session/TabViewInvitations.js
Labels: enhancement, front-end
