Repository SeamusX7/ClubHub, pull requests merged in 2021-04, with the labels that each got.

#278 Removed 'Delete team' button from mini modal #268
  src/screens/launchpad/DisplayTeams.js
Labels: bug

#279 Added copy to clipboard functionailty with alert message acknowledgem…
  package-lock.json
  package.json
  src/screens/launchpad/DisplayTeams.js
Labels: enhancement, front-end

#281 Removed sport field #270
  src/screens/launchpad/CreateTeamForm.js
Labels: front-end

#282 Added team information modal #269
  src/screens/launchpad/DisplayTeams.js
  src/screens/session/NewSessionModal.js
Labels: enhancement, front-end

#284 Created match report modal #277
  src/screens/session/MatchReportModal.js
  src/screens/session/TabViewOverview.js
Labels: enhancement, front-end

#285 Fixed input fields in create session modal #273
  src/components/buttons/DateTimeButton.js
  src/screens/session/NewSessionModal.js
Labels: bug, enhancement, front-end

#286 Redesigned attendance tab #275
  src/screens/session/TabViewAttendance.js
Labels: enhancement, front-end

#287 274 implement location autofill suggestions
  App.js
  package-lock.json
  package.json
  src/assets/talkjs.html
  src/screens/message/ViewMessage.js
  src/screens/session/NewSessionModal.js
Labels: enhancement, front-end

#288 Implemented autofill suggestion feature #274
  src/screens/session/NewSessionModal.js
Labels: enhancement, front-end

#289 Fixed suggestion view #274
  src/screens/session/NewSessionModal.js
Labels: bug, enhancement, front-end

#304 Message system design changes #303
  src/screens/message/Message.js
Labels: enhancement, front-end

#305 Location and opposition only show if sessionType is match #300
  src/components/buttons/DateTimeButton.js
  src/screens/session/NewSessionModal.js
Labels: enhancement, front-end
