Repository SeamusX7/ClubHub, pull requests merged in 2021-02, with the labels that each got.

#185 Hardcoded more player cards under team page #184
  src/screens/team/Team.js
Labels: enhancement, front-end

#191 Notification changes and Player profile rework #187
  src/screens/notification/Notification.js
  src/screens/team/Player.js
Labels: enhancement, front-end

#192 Minor Bug Fix
  src/screens/notification/Notification.js
Labels: enhancement, front-end

#193 Bug Changes
  src/screens/team/Team.js
Labels: bug

#194 Basic checkbox implementation #162
  src/screens/session/InvitePlayerModal.js
Labels: enhancement, front-end

#197 Created and displayed the previous session arrays for all session typ…
  src/screens/session/PreviousGymSessions.js
  src/screens/session/PreviousMatchSessions.js
  src/screens/session/PreviousTrainingSessions.js
Labels: back-end

#199 Added conditional accessibility for player cards #198
  src/components/PlayerCard.js
  src/screens/session/Session.js
  src/screens/team/Team.js
Labels: enhancement

#201 Created userType switch on registration form #200
  src/assets/styles/AuthStyle.js
  src/screens/RegistrationScreen/RegistrationScreen.js
Labels: enhancement, front-end

#205 Initial README setup #204
  README.md
Labels: enhancement
